name: Bug Report
description: Report a bug or unexpected behavior in the Chat SDK
title: "I want to report a bug..."
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a Chat instance with '...'
        2. Register a handler with '...'
        3. Send a webhook request '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to help reproduce the issue
      render: typescript
      placeholder: |
        import { Chat } from 'chat';

        // Your code here...

  - type: input
    id: version
    attributes:
      label: Chat SDK Version
      description: What version of the Chat SDK are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 20.10.0

  - type: dropdown
    id: platform
    attributes:
      label: Platform Adapter
      description: Which platform adapter(s) are you using?
      multiple: true
      options:
        - Slack
        - Microsoft Teams
        - Google Chat
        - Discord
        - GitHub
        - Linear
        - Other

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., screenshots, error messages, console logs)
      placeholder: Any additional information...
